version: '3'
services:
  polyflow:
    container_name: polyflow
    env_file: .env.sample
    build: .
    depends_on:
      - postgres
    ports:
      - '3050:3050'

  experiment:
    container_name: polyflow-experiment
    env_file: .env.experiment
    build: .
    depends_on:
      - postgres
    ports:
      - '3050:3050'

  postgres:
    container_name: polyflow-catalog
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polyflow
    ports:
      - '5432:5432'

networks:
  default:
    external:
      name: polyflow
